// Code generated by MockGen. DO NOT EDIT.
// Source: loan_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	types "github.com/fajryhamzah/go-loan-sim/types"
	gomock "github.com/golang/mock/gomock"
)

// MockLoanRepository is a mock of LoanRepository interface.
type MockLoanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoanRepositoryMockRecorder
}

// MockLoanRepositoryMockRecorder is the mock recorder for MockLoanRepository.
type MockLoanRepositoryMockRecorder struct {
	mock *MockLoanRepository
}

// NewMockLoanRepository creates a new mock instance.
func NewMockLoanRepository(ctrl *gomock.Controller) *MockLoanRepository {
	mock := &MockLoanRepository{ctrl: ctrl}
	mock.recorder = &MockLoanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanRepository) EXPECT() *MockLoanRepositoryMockRecorder {
	return m.recorder
}

// AddLoanToUser mocks base method.
func (m *MockLoanRepository) AddLoanToUser(userId string, Loan *types.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLoanToUser", userId, Loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLoanToUser indicates an expected call of AddLoanToUser.
func (mr *MockLoanRepositoryMockRecorder) AddLoanToUser(userId, Loan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLoanToUser", reflect.TypeOf((*MockLoanRepository)(nil).AddLoanToUser), userId, Loan)
}

// CheckActiveLoanByUserId mocks base method.
func (m *MockLoanRepository) CheckActiveLoanByUserId(userId string) (*types.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActiveLoanByUserId", userId)
	ret0, _ := ret[0].(*types.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckActiveLoanByUserId indicates an expected call of CheckActiveLoanByUserId.
func (mr *MockLoanRepositoryMockRecorder) CheckActiveLoanByUserId(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActiveLoanByUserId", reflect.TypeOf((*MockLoanRepository)(nil).CheckActiveLoanByUserId), userId)
}

// GetLoanById mocks base method.
func (m *MockLoanRepository) GetLoanById(loanId string) (*types.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanById", loanId)
	ret0, _ := ret[0].(*types.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanById indicates an expected call of GetLoanById.
func (mr *MockLoanRepositoryMockRecorder) GetLoanById(loanId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanById", reflect.TypeOf((*MockLoanRepository)(nil).GetLoanById), loanId)
}

// GetLoanPaymentByDate mocks base method.
func (m *MockLoanRepository) GetLoanPaymentByDate(date time.Time) (map[string]*types.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanPaymentByDate", date)
	ret0, _ := ret[0].(map[string]*types.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanPaymentByDate indicates an expected call of GetLoanPaymentByDate.
func (mr *MockLoanRepositoryMockRecorder) GetLoanPaymentByDate(date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanPaymentByDate", reflect.TypeOf((*MockLoanRepository)(nil).GetLoanPaymentByDate), date)
}

// UpdateLoanData mocks base method.
func (m *MockLoanRepository) UpdateLoanData(loanId string, loanData *types.Loan, loanSchedule []*types.LoanPaymentSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoanData", loanId, loanData, loanSchedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoanData indicates an expected call of UpdateLoanData.
func (mr *MockLoanRepositoryMockRecorder) UpdateLoanData(loanId, loanData, loanSchedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoanData", reflect.TypeOf((*MockLoanRepository)(nil).UpdateLoanData), loanId, loanData, loanSchedule)
}
